import test from 'node:test';
import assert from 'node:assert/strict';
import { config } from '../src/config.js';
import { applySampleData, calculateScore, readinessWarnings } from '../src/core.js';
import { createSaasMetrics, buildSaasMarkdown } from '../src/saas-core.js';
test('standalone SaaS dashboard includes actionable productization sections', () => {
    const state = applySampleData(config);
    const score = calculateScore(config, state);
    const warnings = readinessWarnings(config, state);
    const dashboard = createSaasMetrics(config, state, score, warnings);
    assert.equal(dashboard.kpis.length, 7);
    assert.equal(dashboard.segments.length, 3);
    assert.equal(dashboard.experiments.length, 5);
    assert.equal(dashboard.board.length, 5);
    assert.equal(dashboard.milestones.length, 4);
    assert.equal(dashboard.automations.length, 5);
    assert.equal(dashboard.pricing.length, 4);
    assert.equal(dashboard.personas.length, 5);
    assert.equal(dashboard.journeys.length, 4);
    assert.equal(dashboard.featurePackaging.length, 6);
    assert.equal(dashboard.revenueModel.length, 4);
    assert.equal(dashboard.analyticsPlan.length, 5);
    assert.equal(dashboard.securityModel.length, 5);
    assert.equal(dashboard.successPlaybooks.length, 4);
    assert.equal(dashboard.integrations.length, 4);
    assert.equal(dashboard.expansionRoadmap.length, 4);
    assert.equal(dashboard.investorBrief.length, 5);
});
test('SaaS blueprint markdown exports productization roadmap', () => {
    const state = applySampleData(config);
    const markdown = buildSaasMarkdown(config, state, calculateScore(config, state), readinessWarnings(config, state));
    assert.match(markdown, /Standalone SaaS Blueprint/);
    assert.match(markdown, /Customer Segments/);
    assert.match(markdown, /Growth Experiments/);
    assert.match(markdown, /Pricing Ladder/);
    assert.match(markdown, /Persona Matrix/);
    assert.match(markdown, /Revenue Model/);
    assert.match(markdown, /Security & Compliance Model/);
    assert.match(markdown, /Investor \/ Sponsor Brief/);
    assert.match(markdown, new RegExp(config.title.replace(/[.*+?^${}()|\[\]\\]/g, '\\$&')));
});
//# sourceMappingURL=saas.test.js.map